---
- name: Configure Wireless Linux
  hosts: wireless
  become: true
  gather_facts: true
  
  collections:
    - inverse_inc.wireless

  roles:
    - role: mac80211hwsim
    - role: hostapd
    - role: wpasupplicant
