/config/floating_devices:
  get:
    parameters:
    - $ref: '#/components/parameters/cursor'
    responses:
      '200':
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/Iterable'
              - properties:
                  items:
                    properties:
                      id:
                        description: MAC Address
                        type: string
                      ip:
                        description: IP Address
                        type: string
                      pvid:
                        description: VLAN in which PacketFence should put the port
                        type: integer
                      taggedVlan:
                        description: Comma separated list of VLANs. If the port is
                          a multi-vlan, these are the VLANs that have to be tagged
                          on the port.
                        type: string
                      trunkPort:
                        description: The port must be configured as a muti-vlan port
                        type: string
                    required:
                    - id
                    - pvid
                    type: object
                type: object
        description: A list of connection profiles
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  post:
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            properties:
              id:
                description: MAC Address
                type: string
              ip:
                description: IP Address
                type: string
              pvid:
                description: VLAN in which PacketFence should put the port
                type: integer
              taggedVlan:
                description: Comma separated list of VLANs. If the port is a multi-vlan,
                  these are the VLANs that have to be tagged on the port.
                type: string
              trunkPort:
                description: The port must be configured as a muti-vlan port
                type: string
            required:
            - id
            - pvid
            type: object
      required: true
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '409':
        $ref: '#/components/responses/Duplicate'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
