/config/floating_device/{floating_device_id}:
  delete:
    description: Remove an item
    operationId: api.v1.Config::FloatingDevices.remove
    parameters:
    - in: path
      name: floating_device_id
      schema:
        type: string
    responses:
      '204':
        description: Deleted a config item
  description: Configure floating devices
  get:
    description: Get an item
    operationId: api.v1.Config::FloatingDevices.get
    parameters:
    - in: path
      name: floating_device_id
      schema:
        type: string
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigFloatingDevice'
        description: Item
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    description: Update an item
    operationId: api.v1.Config::FloatingDevices.update
    parameters:
    - in: path
      name: floating_device_id
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigFloatingDevice'
    responses:
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    description: Replace an item
    operationId: api.v1.Config::FloatingDevices.replace
    parameters:
    - in: path
      name: floating_device_id
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigFloatingDevice'
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
