/config/provisioning/{provisioning_id}:
  delete:
    description: Remove an item
    operationId: api.v1.Config::Provisionings.remove
    parameters:
    - in: path
      name: provisioning_id
      schema:
        type: string
    responses:
      '204':
        description: Deleted a config item
  description: pf::UnifiedApi::Controller::Config::Provisionings
  get:
    description: Get an item
    operationId: api.v1.Config::Provisionings.get
    parameters:
    - in: path
      name: provisioning_id
      schema:
        type: string
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigProvisioning'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    description: Update an item
    operationId: api.v1.Config::Provisionings.update
    parameters:
    - in: path
      name: provisioning_id
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigProvisioning'
    responses:
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    description: Replace an item
    operationId: api.v1.Config::Provisionings.replace
    parameters:
    - in: path
      name: provisioning_id
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigProvisioning'
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
