/config/sources:
  description: pf::UnifiedApi::Controller::Config::Sources
  get:
    description: List items
    operationId: api.v1.Config::Sources.list
    parameters: []
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigSourcesList'
        description: List
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
