/config/switch_group/{switch_group_id}:
  delete:
    description: Remove an item
    operationId: api.v1.Config::SwitchGroups.remove
    parameters:
    - in: path
      name: switch_group_id
      schema:
        type: string
    responses:
      '204':
        description: Deleted a config item
  description: pf::UnifiedApi::Controller::Config::SwitchGroups
  get:
    description: Get an item
    operationId: api.v1.Config::SwitchGroups.get
    parameters:
    - in: path
      name: switch_group_id
      schema:
        type: string
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigSwitchGroup'
        description: Item
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    description: Update an item
    operationId: api.v1.Config::SwitchGroups.update
    parameters:
    - in: path
      name: switch_group_id
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigSwitchGroup'
    responses:
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    description: Replace an item
    operationId: api.v1.Config::SwitchGroups.replace
    parameters:
    - in: path
      name: switch_group_id
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigSwitchGroup'
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
