/config/switch/{switch_id}:
  delete:
    description: Remove an item
    operationId: api.v1.Config::Switches.remove
    parameters:
    - in: path
      name: switch_id
      schema:
        type: string
    responses:
      '204':
        description: Deleted a config item
  description: |-
    pf::UnifiedApi::Controller::Config::Switches

      invalidate_cache
        invalidate switch cache
  get:
    description: Get an item
    operationId: api.v1.Config::Switches.get
    parameters:
    - in: path
      name: switch_id
      schema:
        type: string
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigSwitch'
        description: Item
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    description: Update an item
    operationId: api.v1.Config::Switches.update
    parameters:
    - in: path
      name: switch_id
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigSwitch'
    responses:
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    description: Replace an item
    operationId: api.v1.Config::Switches.replace
    parameters:
    - in: path
      name: switch_id
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigSwitch'
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
