---
- name: Install packages used for pre-provisioning
  hosts: nodes
  gather_facts: False
  become: True
  collections:
    - inverse_inc.utils

  vars:
    pkg_names:
      - wpasupplicant

  # can be replace later by gitlab-buildpkg-tools role
  tasks:
    - name: Install packages
      apt:
        name: "{{ pkg_names }}"
        state: present
