openapi: "3.0.0"
  
info:
  title: PacketFence API
  description: A JSON HTTP API to access and manipulate the PacketFence resources. Backward compatibility is currently not 100% guaranteed although we will do our best effort to keep API calls as described here.
  version: 1.0.0

paths: {}

components: {}
    
servers:
  - url: https://127.0.0.1:9999/api/v1
      
security:
  - bearerAuth: []
   

      
