---
# Check if CI_COMMIT_TAG is defined (only when making a release) to disable devel repositories
# that contain install dependencies
release_status: '{{ True if lookup("env", "CI_COMMIT_TAG")
                         else False }}'

# set to package name to avoid installing packetfence-release
# from inverse.ca website (already installed based on pipeline
# artifacts)
packetfence_install__centos_release_rpm: 'packetfence-release'

# only for dependencies, packetfence package is installed using local repo
packetfence_install__centos:
  repos: '{{ ["packetfence"] if release_status|bool
                          else ["packetfence-devel"] }}'

# only for dependencies, packetfence packages are installed using local repo
packetfence_install__deb:
  repos: '{{ ["debian"] if release_status|bool
                        else ["debian","debian-devel"] }}'

# we used Venom to pass through configurator
packetfence_install__configurator_status: 'enabled'
